### ISSUE TITLE
v0.4: Toolltip Rendering on Windows

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkToolTip#10]
Hi @Akascape. I am using the latest PyPi version and I am encountering a similar problem with CTkToolTip on Windows as experienced with the CTkMessagebox widget (which you were able to quickly fix).

On Linux I get this:

![LinuxTooltip](https://github.com/Akascape/CTkToolTip/assets/89534395/bfe51228-24f5-4802-855b-222392d036ef)

However, on Windows, the text can be very hard to read:

![WindowsTooltip](https://github.com/Akascape/CTkToolTip/assets/89534395/6bcbdb53-3d61-49d6-ac03-6451c1d82667)

Is it possible to use a similar fix as applied previously on CTkMessagebox , to CTkToolTip?

Thanks.

**Comment by Akascape** [comment]
@avalon60 Lol, same story with this one. Will fix later.

**Comment by avalon60** [comment]
Thanks!

**Comment by avalon60** [comment]
Hi @Akascape. Any idea when a fix will be made available on this?

**Comment by Akascape** [comment]
@Akascape Ok I fixed it, update to the new version 0.5

**Comment by avalon60** [comment]
Hi @Akascape . I just tested and unfortunately it still doesn't work:

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/1bb4e68e-dab9-4674-85b0-d032d7859a35)

I double checked the installed version:

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/81d2a882-79c7-4878-94ad-16643587448c)

**Comment by Akascape** [comment]
@avalon60 Update again, I forgot to add one commit.

**Comment by avalon60** [comment]
Hi @Akascape, it still looks wrong:

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/e39f1881-a333-426f-a862-edc826ec7d3d)

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/8d842e23-d797-4d8a-b363-9bd52bc6d91a)

**Comment by avalon60** [comment]
Here's the theme, if it helps:

[Harlequin.zip](https://github.com/Akascape/CTkToolTip/files/12232521/Harlequin.zip)

**Comment by Akascape** [comment]
@Akascape umm, can you try passing the `alpha=1` parameter in ctktooltip.

**Comment by Akascape** [comment]
@avalon60

**Comment by avalon60** [comment]
@Akascape, that stops it for most instances, except there is an issue with a CTkLabel attached to a tab on a CTkTabview:

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/a3fb59b2-3a32-4ec8-9ea2-17b4886f7c9d)

Code:

```
        # CTkTabview
        self.tabview = ctk.CTkTabview(master=widget_frame, width=250)
        self.tabview.grid(row=10, column=2, padx=(20, 10), pady=(20, 10), sticky="nsew")
        self.tabview.add("CTkTabview")
        self.tabview.add("Tab 2")
        self.tabview.add("Tab 3")
        # self.tabview.tab("CTkTabview").grid_columnconfigure(0, weight=1)  # configure grid of individual tabs
        # self.tabview.tab("Tab 2").grid_columnconfigure(0, weight=1)
        self._rendered_widgets['CTkTabview'].append(self.tabview)
        self.label_tab_1 = ctk.CTkLabel(self.tabview.tab("CTkTabview"), justify='left',
                                        text="I've seen things you people\nwouldn't believe...\n\nAttack ships on fire "
                                             "off\nthe shoulder of Orion...")
        self.label_tab_1.grid(row=0, column=2, padx=20, pady=20)
        self._rendered_widgets['CTkLabel'].append(self.label_tab_1)

        self.label_tab_2 = ctk.CTkLabel(self.tabview.tab("Tab 2"), justify='left',
                                        text="I watched C-beams glitter in\nthe dark near the Tannhäuser\nGate.")
        self.label_tab_2.grid(row=0, column=0, padx=20, pady=20)
        self._rendered_widgets['CTkLabel'].append(self.label_tab_2)

        self.label_tab_3 = ctk.CTkLabel(self.tabview.tab("Tab 3"), justify='left',
                                        text="All those moments will be\nlost in time, like tears\nin rain...\n\n\n"
                                             "Time to die.")
        self.label_tab_3.grid(row=0, column=0, padx=20, pady=20, sticky='nsew')
        self._rendered_widgets['CTkLabel'].append(self.label_tab_3)
        if self._enable_tooltips:
            label_tab_1_tooltip = CTkToolTip(self.label_tab_1,
                                             justify="left",
                                             wraplength=250,
                                             x_offset=-120,
                                             alpha=1,
                                             padding=(5, 5),
                                             message='The CTkTabview is a composite widget. As of CustomTkinter v5, '
                                                     'it has no direct default properties. instead it borrows from '
                                                     'CTkFrame and CTkSegmentedButton.\n\n'
                                                     'The text in the main body of the CTkTabview preview, '
                                                     'is produced via an embedded CTkLabel.')
```

**Comment by Akascape** [comment]
@avalon60 thanks for providing the theme, it was actually a theme issue and I fixed it finally.

**Comment by avalon60** [comment]
@Akascape, this is still not working at my end. None of the tooltips, irrespective of the widget type they are applied to, render clearly - kind of muddied. This also occurs on the CustomTkinter supplied themes. Example, blue theme:

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/fadf38b1-3575-407b-a8c2-2b65da3da698)

Green theme:

![image](https://github.com/Akascape/CTkToolTip/assets/89534395/253cdd5e-e481-4c4b-94ba-b60fa632aee6)

**Comment by Akascape** [comment]
@avalon60 Everything is working, you just need to set alpha=1. It is a transparency effect set to 0.8.

**Comment by avalon60** [comment]
A little transparency, as we have seen, doesn't look good. I am surprised it's enabled by default. For another thing you get inconsistent results across platforms, making it difficult to develop with any consistency,

If this is how it is going to remain, I'll branch my own copy and maintain it locally.

Thanks.

**Comment by Akascape** [comment]
@avalon60 I will change the default to 0.95.

**Comment by avalon60** [comment]
Sure there are differences to some of the base widgets, for reasons of O/S specific look and feel, but why add to that unnecessarily? Especially when the result looks compromised aesthetically, and also when it makes it unusable to-boot .
